language: go
go:
  - 1.6
  - 1.7
install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout 21ff6d397ccca910873d8eaabab6a941c364cc70 && go install && cd -
  - glide install
notifications:
  email:
    on_success: never
    on_failure: change
