version: '2'
services:
  ilo_server_1:
    build: .
    command: ilo-server
    image: ilo
    networks:
      - ilo
  ilo_server_2:
    extends: ilo_server_1
  ilo_server_3:
    extends: ilo_server_1

networks:
  ilo:
    driver: bridge
