version: '2'
services:
  server:
    build: .
    command: ilo-server
    image: ilo
    networks:
      - ilo
  sweep:
    extends: server
    command: ilo-sweep 192.168.0.1/24
networks:
  ilo:
    driver: bridge
