version: '2'
services:
  server:
    build: .
    command: ilo-server
    image: ilo
    networks:
      - ilo
  sweep:
    extends: server
    command: ilo-sweep 172.18.0.0/24
  python_sweep:
    build:
      context: .
      dockerfile: Dockerfile-python
    command: ilo-sweep 172.18.0.0/24 --timeout 10
    image: python-sweep
    networks:
      - ilo
networks:
  ilo:
    driver: bridge
