name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version:
        - '1.18'
        - '1.19'
        - '1.20'
        - '1.21'
        - '1.22'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: go test
      run: go test -race -v ./...
